# 第14回 C#読書会 2017年11月22日(水)

## 予習範囲

* Objective 1.5
    * P.74~P.79 Creating custom exceptionsの始まりまで

## 第14回のまとめ 今回得られた成果

* 前回のtry-catchの続き
    * issueを解決したりエラーのログを取ったりできる場合のときだけ、例外をcatchすべきである。
    * アプリケーションの低レイヤーで一般的なcatchブロックは避けるべきで、高レイヤーでログを取ると、複数のレイヤーで重複したエラーのログが取得されるのを避けることができる。(ここでいうレイヤーとは具体的 <-> 抽象的と読み取れる)

* 1.5 小節 Throw exceptions
    * エラーをthrow(投げる)ときは、例外の新しいインスタンスを生成すること。(1-94はそのサンプルコード)
    * exception objects の再利用はすべきでない。例外を投げるたびに、それを新しく作ること。
        * 特にマルチスレッドな環境では、例外のスタックトレースは他のスレッドから変更が加えられる恐れがあるからである。
    * 例外をcatchするとき、例外を rethrow するという選択が可能である。
        * 以下の3通りの方法を用いて rethrow を行える。
            * identifier 無しに throw を使うやり方。 (例 1-95)
            * オリジナルの例外を用いて throw を使うやり方。
            * 新しく例外を作成し throw を使うやり方。
                * それぞれの詳しい説明は書籍版P.76に記載。
                * 実際にrethrowという文法はないが、概念として登場する。
    * OrderProcessingExceptionを使うことで、より情報を含んだ例外をthrowすることが可能(例 1-96)
    * C#5では例外をrethowする際に使える新しいオプションが追加
        * ExceptionDispatchInfo.Throw メソッドである。これは例外を投げ、オリジナルのスタックトレースを保存 (preserve) することができる。例1-97にサンプルコードが記載されている。
        * このExceptionDispatchInfo.Throwは、ある一つのスレッドで例外をキャッチして、それをもう一つのスレッドに投げる際に使うことができる。このExceptionDispatchInfo.Throwクラスを使うことで、例外のデータ(exception data)をスレッド間で移動したり、投げたりすることができる。.NET FramworkではC＃5で追加された async/await でこれが使われている。asyncスレッドで投げられた例外が、実行中のスレッドでキャプチャされ、rethrowされている。

## 今回学んだ英単語

* preserve

#### 開催概要

* 参加者 : 1人

## 第15回に向けた準備

* Objective 1.5
    * p.78 ~ 80 Chapter Summary
* Chapter 2
    * Objective 2.1 Create types
        * P.89 ~ 93 Giving your types some body
